builds:
  - binary: oscalkit
    main: ./cli/main.go
    ldflags: -s -w -X github.com/docker/oscalkit/cli/version.Version={{.Version}} -X github.com/docker/oscalkit/cli/version.Build={{.ShortCommit}} -X github.com/docker/oscalkit/cli/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

dockers:
  - image: docker/oscalkit
    dockerfile: Dockerfile.release
    tag_templates:
      - "{{ .Version }}"
      - latest

brew:
  name: oscalkit
  github:
    owner: docker
    name: homebrew-oscalkit
  commit_author:
    name: Andrew Weiss
    email: anweiss@docker.com
  homepage: https://github.com/docker/oscalkit
  dependencies:
    - libxml2