
// Code generated by go generate; DO NOT EDIT.
package oscalkit

import (
	"github.com/opencontrol/oscalkit/types/oscal/catalog"
)

var ApplicableControls = []catalog.Catalog{

	catalog.Catalog{
		Title: "",
		Groups: []catalog.Group{
			
				catalog.Group{
					Id:  "Access Control",
					Controls: []catalog.Control{
						
							catalog.Control{
								Id: 	"ac-1",
								Class: 	"SP800-53",
								Title:	"Access Control Policy and Procedures",
								Params: []catalog.Param{
									
										catalog.Param{
											Class: "ac-1_prm_1",
										},
									
										catalog.Param{
											Class: "ac-1_prm_2",
										},
									
										catalog.Param{
											Class: "ac-1_prm_3",
										},
									
								},
								Props: []catalog.Prop{
									
										catalog.Prop{
											Class: "name",
											Id: "",
											Value: "AC-1",
										},
									
								},
							},
						
							catalog.Control{
								Id: 	"ac-2",
								Class: 	"SP800-53",
								Title:	"Account Management",
								Params: []catalog.Param{
									
										catalog.Param{
											Class: "ac-2_prm_1",
										},
									
										catalog.Param{
											Class: "ac-2_prm_2",
										},
									
										catalog.Param{
											Class: "ac-2_prm_3",
										},
									
										catalog.Param{
											Class: "ac-2_prm_4",
										},
									
								},
								Props: []catalog.Prop{
									
										catalog.Prop{
											Class: "name",
											Id: "",
											Value: "AC-2",
										},
									
								},
							},
						
							catalog.Control{
								Id: 	"ac-3",
								Class: 	"SP800-53",
								Title:	"Access Enforcement",
								Params: []catalog.Param{
									
								},
								Props: []catalog.Prop{
									
										catalog.Prop{
											Class: "name",
											Id: "",
											Value: "AC-3",
										},
									
										catalog.Prop{
											Class: "status",
											Id: "",
											Value: "Withdrawn",
										},
									
								},
							},
						
							catalog.Control{
								Id: 	"ac-4",
								Class: 	"SP800-53",
								Title:	"Information Flow Enforcement",
								Params: []catalog.Param{
									
										catalog.Param{
											Class: "ac-4_prm_1",
										},
									
								},
								Props: []catalog.Prop{
									
										catalog.Prop{
											Class: "name",
											Id: "",
											Value: "AC-4",
										},
									
										catalog.Prop{
											Class: "status",
											Id: "",
											Value: "Withdrawn",
										},
									
								},
							},
						
							catalog.Control{
								Id: 	"ac-5",
								Class: 	"SP800-53",
								Title:	"Separation of Duties",
								Params: []catalog.Param{
									
										catalog.Param{
											Class: "ac-5_prm_1",
										},
									
								},
								Props: []catalog.Prop{
									
										catalog.Prop{
											Class: "name",
											Id: "",
											Value: "AC-5",
										},
									
								},
							},
						
							catalog.Control{
								Id: 	"ac-6",
								Class: 	"SP800-53",
								Title:	"Least Privilege",
								Params: []catalog.Param{
									
								},
								Props: []catalog.Prop{
									
										catalog.Prop{
											Class: "name",
											Id: "",
											Value: "AC-6",
										},
									
								},
							},
						
							catalog.Control{
								Id: 	"ac-7",
								Class: 	"SP800-53",
								Title:	"Unsuccessful Logon Attempts",
								Params: []catalog.Param{
									
										catalog.Param{
											Class: "ac-7_prm_1",
										},
									
										catalog.Param{
											Class: "ac-7_prm_2",
										},
									
										catalog.Param{
											Class: "ac-7_prm_3",
										},
									
										catalog.Param{
											Class: "ac-7_prm_4",
										},
									
										catalog.Param{
											Class: "ac-7_prm_5",
										},
									
								},
								Props: []catalog.Prop{
									
										catalog.Prop{
											Class: "name",
											Id: "",
											Value: "AC-7",
										},
									
										catalog.Prop{
											Class: "status",
											Id: "",
											Value: "Withdrawn",
										},
									
								},
							},
						
							catalog.Control{
								Id: 	"ac-8",
								Class: 	"SP800-53",
								Title:	"System Use Notification",
								Params: []catalog.Param{
									
										catalog.Param{
											Class: "ac-8_prm_1",
										},
									
										catalog.Param{
											Class: "ac-8_prm_2",
										},
									
								},
								Props: []catalog.Prop{
									
										catalog.Prop{
											Class: "name",
											Id: "",
											Value: "AC-8",
										},
									
								},
							},
						
							catalog.Control{
								Id: 	"ac-10",
								Class: 	"SP800-53",
								Title:	"Concurrent Session Control",
								Params: []catalog.Param{
									
										catalog.Param{
											Class: "ac-10_prm_1",
										},
									
										catalog.Param{
											Class: "ac-10_prm_2",
										},
									
								},
								Props: []catalog.Prop{
									
										catalog.Prop{
											Class: "name",
											Id: "",
											Value: "AC-10",
										},
									
								},
							},
						
							catalog.Control{
								Id: 	"ac-11",
								Class: 	"SP800-53",
								Title:	"Session Lock",
								Params: []catalog.Param{
									
										catalog.Param{
											Class: "ac-11_prm_1",
										},
									
								},
								Props: []catalog.Prop{
									
										catalog.Prop{
											Class: "name",
											Id: "",
											Value: "AC-11",
										},
									
								},
							},
						
					},
				},
			
				catalog.Group{
					Id:  "Awareness and Training",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Audit and Accountability",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Security Assessment and Authorization",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Configuration Management",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Contingency Planning",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Identification and Authentication",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Incident Response",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Maintenance",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Media Protection",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Physical and Environmental Protection",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Planning",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Personnel Security",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Risk Assessment",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "System and Services Acquisition",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "System and Communications Protection",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "System and Information Integrity",
					Controls: []catalog.Control{
						
					},
				},
			
				catalog.Group{
					Id:  "Program Management",
					Controls: []catalog.Control{
						
					},
				},
			
		},
	},

}
