// Code generated by go generate; DO NOT EDIT.
package system_security_plan

import (
	"github.com/docker/oscalkit/types/oscal/validation_root"
)

// A system security plan, such as those described in NIST SP 800-18
type SystemSecurityPlan struct {

	// Unique identifier of the containing object
	Id string `xml:"id,attr,omitempty" json:"id,omitempty"`

	// Provides information about the publication and availability of the containing document.
	Metadata *validation_root.Metadata `xml:"metadata,omitempty" json:"metadata,omitempty"`
	// Used to import the OSCAL profile representing the system's control baseline.
	ImportProfile *ImportProfile `xml:"import-profile,omitempty" json:"importProfile,omitempty"`
	// Contains the characteristics of the system, such as its name, purpose, and security impact level.
	SystemCharacteristics *SystemCharacteristics `xml:"system-characteristics,omitempty" json:"systemCharacteristics,omitempty"`
	// Provides information as to how the system is implemented.
	SystemImplementation *SystemImplementation `xml:"system-implementation,omitempty" json:"systemImplementation,omitempty"`
	// Describes how the system satisfies a set of controls.
	ControlImplementation *ControlImplementation `xml:"control-implementation,omitempty" json:"controlImplementation,omitempty"`
	// A collection of citations and resource references.
	BackMatter *validation_root.BackMatter `xml:"back-matter,omitempty" json:"backMatter,omitempty"`
}

// Used to import the OSCAL profile representing the system's control baseline.
type ImportProfile struct {

	// A link to a document or document fragment (actual, nominal or projected)
	Href string `xml:"href,attr,omitempty" json:"href,omitempty"`

	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
}

// Contains the characteristics of the system, such as its name, purpose, and security impact level.
type SystemCharacteristics struct {

	// A unique identifier for the system described by this system security plan.
	SystemId []SystemId `xml:"system-ids,omitempty" json:"systemIds,omitempty"`
	// The full name of the system.
	SystemName SystemName `xml:"system-name,omitempty" json:"systemName,omitempty"`
	// A short name for the system, such as an acronym, that is suitable for display in a data table or summary list.
	SystemNameShort SystemNameShort `xml:"system-name-short,omitempty" json:"systemNameShort,omitempty"`
	// A free-text description of the system.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// The date this system received its authorization.
	DateAuthorized DateAuthorized `xml:"date-authorized,omitempty" json:"dateAuthorized,omitempty"`
	// The overall information system sensitivity categorization, such as defined by .
	SecuritySensitivityLevel SecuritySensitivityLevel `xml:"security-sensitivity-level,omitempty" json:"securitySensitivityLevel,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// Contains details about all information types that are stored, processed, or transmitted by the system, such as privacy information, and those defined in .
	SystemInformation *SystemInformation `xml:"system-information,omitempty" json:"systemInformation,omitempty"`
	// The overall level of expected impact resulting from unauthorized disclosure, modification, or loss of access to information.
	SecurityImpactLevel *SecurityImpactLevel `xml:"security-impact-level,omitempty" json:"securityImpactLevel,omitempty"`
	// Describes the operational status of the system.
	Status *Status `xml:"status,omitempty" json:"status,omitempty"`
	// A description of another authorized system from which this system inherits capabilities that satisfy security requirements. Another term for this concept is a .
	LeveragedAuthorization []LeveragedAuthorization `xml:"leveraged-authorizations,omitempty" json:"leveragedAuthorizations,omitempty"`
	// A description of this system's authorization boundary, optionally supplemented by diagrams that illustrate the authorization boundary.
	AuthorizationBoundary *AuthorizationBoundary `xml:"authorization-boundary,omitempty" json:"authorizationBoundary,omitempty"`
	// A description of the system's network architecture, optionally supplemented by diagrams that illustrate the network architecture.
	NetworkArchitecture *NetworkArchitecture `xml:"network-architecture,omitempty" json:"networkArchitecture,omitempty"`
	// A description of the logical flow of information within the system and across its boundaries, optionally supplemented by diagrams that illustrate these flows.
	DataFlow *DataFlow `xml:"data-flow,omitempty" json:"dataFlow,omitempty"`
	// A reference to a set of organizations or persons that have responsibility for performing a referenced role relative to the parent context.
	ResponsibleParty []validation_root.ResponsibleParty `xml:"responsible-parties,omitempty" json:"responsibleParties,omitempty"`
}

// Contains details about all information types that are stored, processed, or transmitted by the system, such as privacy information, and those defined in .
type SystemInformation struct {

	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// Contains details about one information type that is stored, processed, or transmitted by the system, such as privacy information, and those defined in .
	InformationType []InformationType `xml:"information-types,omitempty" json:"informationTypes,omitempty"`
}

// Contains details about one information type that is stored, processed, or transmitted by the system, such as privacy information, and those defined in .
type InformationType struct {

	// Unique identifier of the containing object
	Id string `xml:"id,attr,omitempty" json:"id,omitempty"`
	// The name of the information type.
	Name string `xml:"name,attr,omitempty" json:"name,omitempty"`

	// A description supporting the parent item.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// An identifier qualified by the given identification  used, such as NIST SP 800-60.
	InformationTypeId []InformationTypeId `xml:"information-type-ids,omitempty" json:"informationTypeIds,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// The expected level of impact resulting from the unauthorized disclosure of information.
	ConfidentialityImpact *ConfidentialityImpact `xml:"confidentiality-impact,omitempty" json:"confidentialityImpact,omitempty"`
	// The expected level of impact resulting from the unauthorized modification of information.
	IntegrityImpact *IntegrityImpact `xml:"integrity-impact,omitempty" json:"integrityImpact,omitempty"`
	// The expected level of impact resulting from the disruption of access to or use of information or the information system.
	AvailabilityImpact *AvailabilityImpact `xml:"availability-impact,omitempty" json:"availabilityImpact,omitempty"`
}

// The expected level of impact resulting from the unauthorized disclosure of information.
type ConfidentialityImpact struct {

	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// The prescribed base (Confidentiality, Integrity, or Availability) security impact level.
	Base Base `xml:"base,omitempty" json:"base,omitempty"`
	// The selected (Confidentiality, Integrity, or Availability) security impact level.
	Selected Selected `xml:"selected,omitempty" json:"selected,omitempty"`
	// If the selected security level is different from the base security level, this contains the justification for the change.
	AdjustmentJustification AdjustmentJustification `xml:"adjustment-justification,omitempty" json:"adjustmentJustification,omitempty"`
}

// The expected level of impact resulting from the unauthorized modification of information.
type IntegrityImpact struct {

	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// The prescribed base (Confidentiality, Integrity, or Availability) security impact level.
	Base Base `xml:"base,omitempty" json:"base,omitempty"`
	// The selected (Confidentiality, Integrity, or Availability) security impact level.
	Selected Selected `xml:"selected,omitempty" json:"selected,omitempty"`
	// If the selected security level is different from the base security level, this contains the justification for the change.
	AdjustmentJustification AdjustmentJustification `xml:"adjustment-justification,omitempty" json:"adjustmentJustification,omitempty"`
}

// The expected level of impact resulting from the disruption of access to or use of information or the information system.
type AvailabilityImpact struct {

	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// The prescribed base (Confidentiality, Integrity, or Availability) security impact level.
	Base Base `xml:"base,omitempty" json:"base,omitempty"`
	// The selected (Confidentiality, Integrity, or Availability) security impact level.
	Selected Selected `xml:"selected,omitempty" json:"selected,omitempty"`
	// If the selected security level is different from the base security level, this contains the justification for the change.
	AdjustmentJustification AdjustmentJustification `xml:"adjustment-justification,omitempty" json:"adjustmentJustification,omitempty"`
}

// The overall level of expected impact resulting from unauthorized disclosure, modification, or loss of access to information.
type SecurityImpactLevel struct {

	// A target-level of confidentiality for the system, based on the sensitivity of information within the system.
	SecurityObjectiveConfidentiality SecurityObjectiveConfidentiality `xml:"security-objective-confidentiality,omitempty" json:"securityObjectiveConfidentiality,omitempty"`
	// A target-level of integrity for the system, based on the sensitivity of information within the system.
	SecurityObjectiveIntegrity SecurityObjectiveIntegrity `xml:"security-objective-integrity,omitempty" json:"securityObjectiveIntegrity,omitempty"`
	// A target-level of availability for the system, based on the sensitivity of information within the system.
	SecurityObjectiveAvailability SecurityObjectiveAvailability `xml:"security-objective-availability,omitempty" json:"securityObjectiveAvailability,omitempty"`
}

// Describes the operational status of the system.
type Status struct {

	// The current operating status.
	State string `xml:"state,attr,omitempty" json:"state,omitempty"`

	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
}

// A description of another authorized system from which this system inherits capabilities that satisfy security requirements. Another term for this concept is a .
type LeveragedAuthorization struct {

	// Unique identifier of the containing object
	Id string `xml:"id,attr,omitempty" json:"id,omitempty"`
	// Identifying the purpose and intended use of the property, part or other object.
	Name string `xml:"name,attr,omitempty" json:"name,omitempty"`

	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// A reference to the party that manages the leveraged system.
	PartyId validation_root.PartyId `xml:"party-id,omitempty" json:"partyId,omitempty"`
	// The date this system received its authorization.
	DateAuthorized DateAuthorized `xml:"date-authorized,omitempty" json:"dateAuthorized,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
}

// A description of this system's authorization boundary, optionally supplemented by diagrams that illustrate the authorization boundary.
type AuthorizationBoundary struct {

	// A description supporting the parent item.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// Commentary about the system's authorization boundary that enhances the diagram.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// A visual depiction of the system's authorization boundary.
	Diagram []Diagram `xml:"diagrams,omitempty" json:"diagrams,omitempty"`
}

// A graphic that provides a visual representation the system, or some aspect of it.
type Diagram struct {

	// An identifier for this diagram.
	Id string `xml:"id,attr,omitempty" json:"id,omitempty"`

	// A description of the diagram (e.g., alternate text). This can be used to support compliance with requirements from Section 508 of the United States Workforce Rehabilitation Act of 1973.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// A brief caption to annotate the diagram.
	Caption Caption `xml:"caption,omitempty" json:"caption,omitempty"`
	// Commentary about the diagram that enhances it.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
}

// A description of the system's network architecture, optionally supplemented by diagrams that illustrate the network architecture.
type NetworkArchitecture struct {

	// A description supporting the parent item.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// A graphic that provides a visual representation the system, or some aspect of it.
	Diagram []Diagram `xml:"diagrams,omitempty" json:"diagrams,omitempty"`
}

// A description of the logical flow of information within the system and across its boundaries, optionally supplemented by diagrams that illustrate these flows.
type DataFlow struct {

	// A description supporting the parent item.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// A graphic that provides a visual representation the system, or some aspect of it.
	Diagram []Diagram `xml:"diagrams,omitempty" json:"diagrams,omitempty"`
}

// Provides information as to how the system is implemented.
type SystemImplementation struct {

	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// A type of user that interacts with the system based on an associated role.
	User []User `xml:"users,omitempty" json:"users,omitempty"`
	// A defined component that can be part of an implemented system.
	Component []Component `xml:"components,omitempty" json:"components,omitempty"`
	// A collection of the ports, protocols, and services used within the system.
	Service []Service `xml:"services,omitempty" json:"services,omitempty"`
	// Details on an individual system interconnection.
	Interconnection []Interconnection `xml:"ssp-interconnection,omitempty" json:"sspInterconnection,omitempty"`
	// A set of  entries that represent the managed inventory instances of the system.
	SystemInventory *SystemInventory `xml:"system-inventory,omitempty" json:"systemInventory,omitempty"`
}

// A type of user that interacts with the system based on an associated role.
type User struct {

	// A unique identifier that references this user class.
	Id string `xml:"id,attr,omitempty" json:"id,omitempty"`

	// A title for display and navigation
	Title validation_root.Title `xml:"title,omitempty" json:"title,omitempty"`
	// A common name, short name or acronym
	ShortName validation_root.ShortName `xml:"short-name,omitempty" json:"shortName,omitempty"`
	// A description supporting the parent item.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// A reference to the roles served by the user.
	RoleId []RoleId `xml:"role-ids,omitempty" json:"roleIds,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// Identifies a specific system privilege held by the user, along with an associated description and/or rationale for the privilege.
	AuthorizedPrivilege []AuthorizedPrivilege `xml:"authorized-privileges,omitempty" json:"authorizedPrivileges,omitempty"`
}

// Identifies a specific system privilege held by the user, along with an associated description and/or rationale for the privilege.
type AuthorizedPrivilege struct {

	// The name of the identified privilege.
	Name string `xml:"name,attr,omitempty" json:"name,omitempty"`

	// A description supporting the parent item.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// Describes a  function performed for a given authorized privilege by this user class.
	FunctionPerformed []FunctionPerformed `xml:"functions-performed,omitempty" json:"functionsPerformed,omitempty"`
}

// A defined component that can be part of an implemented system.
type Component struct {

	// A unique identifier for a component.
	Id string `xml:"id,attr,omitempty" json:"id,omitempty"`
	// The component's human-readable name.
	Name string `xml:"name,attr,omitempty" json:"name,omitempty"`
	// A category describing the purpose of the component.
	ComponentType string `xml:"component-type,attr,omitempty" json:"componentType,omitempty"`

	// A description of the component, including information about its function.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// Describes the operational status of the system.
	Status *Status `xml:"status,omitempty" json:"status,omitempty"`
	// Defines a role that has responsibility for the component.
	ResponsibleRole []ResponsibleRole `xml:"responsible-roles,omitempty" json:"responsibleRoles,omitempty"`
}

// Information about an individual service within the system.
type Service struct {

	// Unique identifier of the containing object
	Id string `xml:"id,attr,omitempty" json:"id,omitempty"`
	// Identifying the purpose and intended use of the property, part or other object.
	Name string `xml:"name,attr,omitempty" json:"name,omitempty"`

	// A description of what the service provides.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// A summary of the technological or business purpose of the service.
	Purpose Purpose `xml:"purpose,omitempty" json:"purpose,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// Information about the protocol used to provide a service.
	Protocol []Protocol `xml:"ssp-protocol,omitempty" json:"sspProtocol,omitempty"`
}

// Information about the protocol used to provide a service.
type Protocol struct {

	// Identifying the purpose and intended use of the property, part or other object.
	Name string `xml:"name,attr,omitempty" json:"name,omitempty"`

	// Where applicable this is the IPv4 port range on which the service operates.
	PortRange []PortRange `xml:"port-ranges,omitempty" json:"portRanges,omitempty"`
}

// Details on an individual system interconnection.
type Interconnection struct {

	// Unique identifier of the containing object
	Id string `xml:"id,attr,omitempty" json:"id,omitempty"`

	// The name of the remote interconnected system.
	RemoteSystemName RemoteSystemName `xml:"remote-system-name,omitempty" json:"remoteSystemName,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// A reference to a set of organizations or persons that have responsibility for performing a referenced role relative to the parent context.
	ResponsibleParty []validation_root.ResponsibleParty `xml:"responsible-parties,omitempty" json:"responsibleParties,omitempty"`
}

// A set of  entries that represent the managed inventory instances of the system.
type SystemInventory struct {

	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A single managed inventory item within the system.
	InventoryItem []InventoryItem `xml:"inventory-items,omitempty" json:"inventoryItems,omitempty"`
}

// A single managed inventory item within the system.
type InventoryItem struct {

	// Unique identifier of the containing object
	Id string `xml:"id,attr,omitempty" json:"id,omitempty"`
	// Organizational asset identifier that is unique in the context of the system. This may be a reference to the identifier used in an asset tracking system or a vulnerability scanning tool.
	AssetId string `xml:"asset-id,attr,omitempty" json:"assetId,omitempty"`

	// A description supporting the parent item.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// A reference to a set of organizations or persons that have responsibility for performing a referenced role relative to the parent context.
	ResponsibleParty []validation_root.ResponsibleParty `xml:"responsible-parties,omitempty" json:"responsibleParties,omitempty"`
	// The set of componenets that are implemented in a given system inventory item.
	ImplementedComponent []ImplementedComponent `xml:"implemented-components,omitempty" json:"implementedComponents,omitempty"`
}

// The set of componenets that are implemented in a given system inventory item.
type ImplementedComponent struct {

	// A reference to a component that is implemented as part of an inventory item.
	ComponentId string `xml:"component-id,attr,omitempty" json:"componentId,omitempty"`
	// The type of implementation
	Use string `xml:"use,attr,omitempty" json:"use,omitempty"`

	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// A reference to a set of organizations or persons that have responsibility for performing a referenced role relative to the parent context.
	ResponsibleParty []validation_root.ResponsibleParty `xml:"responsible-parties,omitempty" json:"responsibleParties,omitempty"`
}

// Describes how the system satisfies a set of controls.
type ControlImplementation struct {

	// A description supporting the parent item.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// Describes how the system satisfies an individual control.
	ImplementedRequirement []ImplementedRequirement `xml:"implemented-requirements,omitempty" json:"implementedRequirements,omitempty"`
}

// Describes how the system satisfies an individual control.
type ImplementedRequirement struct {

	// Unique identifier of the containing object
	Id string `xml:"id,attr,omitempty" json:"id,omitempty"`
	// A reference to a control identifier.
	ControlId string `xml:"control-id,attr,omitempty" json:"controlId,omitempty"`

	// A description supporting the parent item.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// Defines how the referenced component implements a set of controls.
	ByComponent []ByComponent `xml:"by-components,omitempty" json:"byComponents,omitempty"`
	// A reference to one or more roles with responsibility for performing a function relative to the control.
	ResponsibleRole []ResponsibleRole `xml:"responsible-roles,omitempty" json:"responsibleRoles,omitempty"`
	// Identifies the parameter that will be filled in by the enclosed value element.
	SetParam []SetParam `xml:"set-params,omitempty" json:"setParams,omitempty"`
	// Identifies which statements within a control are addressed.
	Statement []Statement `xml:"statements,omitempty" json:"statements,omitempty"`
}

// Identifies which statements within a control are addressed.
type Statement struct {

	// A reference to the specific implemented statement associated with a control.
	StatementId string `xml:"statement-id,attr,omitempty" json:"statementId,omitempty"`

	// A description supporting the parent item.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A reference to one or more roles with responsibility for performing a function relative to the control.
	ResponsibleRole []ResponsibleRole `xml:"responsible-roles,omitempty" json:"responsibleRoles,omitempty"`
	// Defines how the referenced component implements a set of controls.
	ByComponent []ByComponent `xml:"by-components,omitempty" json:"byComponents,omitempty"`
}

// A reference to one or more roles with responsibility for performing a function relative to the control.
type ResponsibleRole struct {

	// The role that is responsible for the business function.
	RoleId string `xml:"role-id,attr,omitempty" json:"roleId,omitempty"`

	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// References a  defined in .
	PartyId []validation_root.PartyId `xml:"party-ids,omitempty" json:"partyIds,omitempty"`
	// Additional commentary on the parent item.
	Remarks validation_root.Remarks `xml:"remarks,omitempty" json:"remarks,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
}

// Defines how the referenced component implements a set of controls.
type ByComponent struct {

	// A reference to the component that is implementing a given control or control statement.
	ComponentId string `xml:"component-id,attr,omitempty" json:"componentId,omitempty"`

	// A description supporting the parent item.
	Description validation_root.Description `xml:"description,omitempty" json:"description,omitempty"`
	// A value with a name, attributed to the containing control, part, or group.
	Prop []validation_root.Prop `xml:"properties,omitempty" json:"properties,omitempty"`
	// A reference to a local or remote resource
	Link []validation_root.Link `xml:"links,omitempty" json:"links,omitempty"`
	// A name/value pair with optional explanatory remarks.
	Annotation []validation_root.Annotation `xml:"annotations,omitempty" json:"annotations,omitempty"`
	// A reference to one or more roles with responsibility for performing a function relative to the control.
	ResponsibleRole []ResponsibleRole `xml:"responsible-roles,omitempty" json:"responsibleRoles,omitempty"`
	// Identifies the parameter that will be filled in by the enclosed value element.
	SetParam []SetParam `xml:"set-params,omitempty" json:"setParams,omitempty"`
}

// Identifies the parameter that will be filled in by the enclosed value element.
type SetParam struct {

	// Points to a parameter within a control, to which the contained value will be assigned.
	ParamId string `xml:"param-id,attr,omitempty" json:"paramId,omitempty"`

	// The phrase or string that fills-in the parameter and completes the requirement statement.
	Value Value `xml:"value,omitempty" json:"value,omitempty"`
}

// A unique identifier for the system described by this system security plan.
type SystemId struct {
	// Identifies the identification system from which the provided identifier was assigned.
	IdentifierType string `xml:"identifier-type,attr,omitempty" json:"identifierType,omitempty"`
	Value          string `xml:",chardata" json:"value,omitempty"`
}

// The full name of the system.

type SystemName string

// A short name for the system, such as an acronym, that is suitable for display in a data table or summary list.

type SystemNameShort string

// The overall information system sensitivity categorization, such as defined by .

type SecuritySensitivityLevel string

// An identifier qualified by the given identification  used, such as NIST SP 800-60.
type InformationTypeId struct {
	// Specifies the information type identification system used.
	System string `xml:"system,attr,omitempty" json:"system,omitempty"`
	Value  string `xml:",chardata" json:"value,omitempty"`
}

// The prescribed base (Confidentiality, Integrity, or Availability) security impact level.

type Base string

// The selected (Confidentiality, Integrity, or Availability) security impact level.

type Selected string

// If the selected security level is different from the base security level, this contains the justification for the change.

type AdjustmentJustification string

// A target-level of confidentiality for the system, based on the sensitivity of information within the system.

type SecurityObjectiveConfidentiality string

// A target-level of integrity for the system, based on the sensitivity of information within the system.

type SecurityObjectiveIntegrity string

// A target-level of availability for the system, based on the sensitivity of information within the system.

type SecurityObjectiveAvailability string

// The date this system received its authorization.

type DateAuthorized string

// A brief caption to annotate the diagram.

type Caption string

// A reference to the roles served by the user.

type RoleId string

// Describes a  function performed for a given authorized privilege by this user class.

type FunctionPerformed string

// Where applicable this is the IPv4 port range on which the service operates.
type PortRange struct {
	// Indicates the starting port number in a port range
	Start uint64 `xml:"start,attr,omitempty" json:"start,omitempty"`

	// Indicates the ending port number in a port range
	End uint64 `xml:"end,attr,omitempty" json:"end,omitempty"`

	// Indicates the transport type.
	Transport string `xml:"transport,attr,omitempty" json:"transport,omitempty"`
	Value     string `xml:",chardata" json:"value,omitempty"`
}

// Describes the purpose for the service within the system.

type Purpose string

// The name of the remote interconnected system.

type RemoteSystemName string

// The phrase or string that fills-in the parameter and completes the requirement statement.

type Value string
