package templates

import (
	"html/template"
)

//GetProfileTemplate GetProfileTemplate
func GetProfileTemplate() *template.Template {

	return template.Must(template.New("").Parse(profileTemplate))
}

const profileTemplate = `
// Code generated by go generate; DO NOT EDIT.
package {{.PackageName}}

import (
	"net/url"

	"github.com/docker/oscalkit/types/oscal/catalog"
	"github.com/docker/oscalkit/types/oscal/profile"

)


var ApplicableProfileControls = profile.Profile{
	Imports: []profile.Import{
		{
			{{range .Profile.Imports}}
				Exclude: &profile.Exclude{
					IdSelectors: []profile.Call{
					},
				},
				Include: &profile.Include{
					IdSelectors: []profile.Call{
						{{range .Include.IdSelectors}}
							{
									ControlId: "{{.ControlId}}",
									ControlId: "{{.ControlId}}",
							},
						{{end}}

					},
				},
				Href: &catalog.Href{
					URL: &url.URL{
						RawPath: "{{.Href}}",
					},
				},
			{{end}}
			},
	},
	Merge: &profile.Merge{
		AsIs: profile.AsIs("{{.Profile.Merge.AsIs}}"), 
	},
	Modify: &profile.Modify{
		Alterations: []profile.Alter{
			{{range .Profile.Modify.Alterations}}
				{
					ControlId: "123",
					Additions: []profile.Add{
						{{range .Additions}}
							{
								Title: "{{.Title}}",
								Position: "{{.Position}}",
								Props: []catalog.Prop{
									{{range .Props}}
										{
											Class: "{{.Class}}",
											Id:    "{{.Id}}",
											Value: "{{.Value}}",
										},
									{{end}}
								},
		
							},
						{{end}}
					},
				},
			{{end}}
		},
	},
}
`
